import { esc, lc, safeUrl, slug } from "./text.mjs";

const HIDDEN_TOPIC = "profile-hidden";

const time = (s) => (s ? Date.parse(s) || 0 : 0);
const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const monthYear = (iso) => {
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? "" : `${MONTHS[d.getUTCMonth()]} ${d.getUTCFullYear()}`;
};

/** Public, original repositories worth listing, newest push first, minus anything already shown as a card. */
export function recentRepos(repos, cfg) {
  const skip = new Set([lc(cfg.username), ...(cfg.recent?.hidden ?? []).map(lc), ...cfg.projects.map((p) => lc(p.repo))]);
  return repos
    .filter(
      (r) =>
        !r.fork &&
        !r.archived &&
        !r.disabled &&
        !r.private &&
        (r.visibility ?? "public") === "public" &&
        !skip.has(lc(r.name)) &&
        !(r.topics ?? []).includes(HIDDEN_TOPIC),
    )
    .sort((a, b) => time(b.pushed_at) - time(a.pushed_at) || lc(a.name).localeCompare(lc(b.name)))
    .slice(0, cfg.recent?.limit ?? 6);
}

// Themed image: GitHub swaps the <source> to match the viewer's light/dark setting.
const picture = (base, alt, width) => `<picture>
  <source media="(prefers-color-scheme: dark)" srcset="${base}-dark.svg">
  <img src="${base}-light.svg" alt="${esc(alt)}" width="${width}">
</picture>`;

const LINKS = {
  website: { label: "Website", logo: "googlechrome" },
  email: { label: "Email", logo: "gmail", url: (v) => `mailto:${v.replace(/^mailto:/, "")}` },
  linkedin: { label: "LinkedIn", logo: "" },
  x: { label: "X", logo: "x", url: (v) => (/^https?:/.test(v) ? v : `https://x.com/${v.replace(/^@/, "")}`) },
  bluesky: { label: "Bluesky", logo: "bluesky" },
  instagram: { label: "Instagram", logo: "instagram" },
  youtube: { label: "YouTube", logo: "youtube" },
  devto: { label: "DEV", logo: "devdotto" },
  hashnode: { label: "Hashnode", logo: "hashnode" },
  medium: { label: "Medium", logo: "medium" },
  discord: { label: "Discord", logo: "discord" },
  resume: { label: "Résumé", logo: "readdotcv" },
};

export function linkBadges(links = {}, warn = console.warn) {
  const out = [];
  for (const [key, value] of Object.entries(links)) {
    const raw = String(value ?? "").trim();
    if (!raw) continue;
    const def = LINKS[key];
    if (!def) {
      warn(`unknown link "${key}" in profile.config.json (supported: ${Object.keys(LINKS).join(", ")})`);
      continue;
    }
    const href = safeUrl(def.url ? def.url(raw) : raw);
    if (!href) {
      warn(`link "${key}" is not a valid URL: ${raw}`);
      continue;
    }
    const label = encodeURIComponent(def.label.replace(/-/g, "--").replace(/_/g, "__"));
    let img = `https://img.shields.io/badge/${label}-11141B?style=for-the-badge`;
    if (def.logo) img += `&logo=${def.logo}&logoColor=FF7A45`;
    out.push(`<a href="${esc(href)}"><img src="${esc(img)}" alt="${esc(def.label)}" height="30"></a>`);
  }
  return out;
}

export function renderReadme(cfg, { repos = [], warn = console.warn, snake = Boolean(cfg.activity?.snake) } = {}) {
  const u = cfg.username;
  const name = cfg.name?.trim() || u;
  const out = [
    "<!--",
    "  Generated by scripts/build.mjs from profile.config.json.",
    "  Don't edit this file by hand: change the config and run `npm run build`",
    "  (or push, and the GitHub Action rebuilds it for you).",
    "-->",
    "",
    `<a href="https://github.com/${u}">`,
    picture("assets/hero", `${name}: ${cfg.hero?.tagline ?? ""}`, "100%"),
    "</a>",
    "",
  ];

  const badges = linkBadges(cfg.links, warn);
  if (badges.length) out.push(`<p align="center">\n${badges.join("\n")}\n</p>`, "");

  // About
  const about = cfg.about ?? {};
  if (about.intro?.length || about.now?.length) {
    out.push(`## ${about.heading ?? "About"}`, "");
    for (const p of about.intro ?? []) out.push(p, "");
    if (about.now?.length) {
      out.push("<table><tr><td>", "", about.nowHeading ? `**${about.nowHeading}**\n` : "");
      for (const item of about.now) out.push(`- ${item}`);
      out.push("", "</td></tr></table>", "");
    }
  }

  // Featured project cards
  if (cfg.projects.length) {
    out.push(`## ${cfg.projectsHeading ?? "Building"}`, "", "<p>");
    for (const p of cfg.projects) {
      const img = picture(`assets/cards/${slug(p.name)}`, `${p.name}: ${p.description}`, "49%");
      const href = safeUrl(p.url) ?? (p.repo ? `https://github.com/${u}/${p.repo}` : null);
      out.push(href ? `<a href="${esc(href)}">${img}</a>` : img);
    }
    out.push("</p>", "");
  }

  // Everything else that's public, pulled from the API
  const recent = recentRepos(repos, cfg);
  if (recent.length) {
    out.push(`## ${cfg.recent?.heading ?? "Recently pushed"}`, "");
    out.push("| Project | What it is | |", "|:--|:--|--:|");
    for (const r of recent) {
      const meta = [r.language, r.stargazers_count > 0 ? `★ ${r.stargazers_count}` : "", monthYear(r.pushed_at)].filter(Boolean).join(" · ");
      const desc = (r.description ?? "").replace(/\|/g, "\\|").replace(/\s+/g, " ").trim();
      out.push(`| [**${esc(r.name)}**](${r.html_url}) | ${esc(desc) || "—"} | <sub>${esc(meta)}</sub> |`);
    }
    out.push("", `<sub><a href="https://github.com/${u}?tab=repositories&type=source">All repositories →</a></sub>`, "");
  }

  // Toolbox
  if (cfg.stack?.length) {
    out.push(`## ${cfg.stackHeading ?? "Toolbox"}`, "", picture("assets/stack", `Tech stack: ${cfg.stack.map((g) => g.items.join(", ")).join("; ")}`, "100%"), "");
  }

  // Contribution snake (built by .github/workflows/snake.yml onto the `output` branch)
  if (snake) {
    const base = `https://raw.githubusercontent.com/${u}/${u}/output/snake`;
    out.push(
      `## ${cfg.activity.heading ?? "Activity"}`,
      "",
      `<picture>
  <source media="(prefers-color-scheme: dark)" srcset="${base}-dark.svg">
  <img src="${base}-light.svg" alt="A snake eating ${esc(u)}'s GitHub contribution graph" width="100%">
</picture>`,
      "",
    );
  }

  // Sign-off
  if (cfg.contact?.note) out.push("<br>", "", `<p align="center">${esc(cfg.contact.note)}</p>`, "");
  out.push(picture("assets/footer", cfg.footer ?? "", "100%"), "");

  return `${out.join("\n").replace(/\n{3,}/g, "\n\n").trim()}\n`;
}
