import { test } from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { wrap, esc, slug } from "./lib/text.mjs";
import { renderHero } from "./lib/hero.mjs";
import { renderCard, renderStack, renderFooter } from "./lib/panels.mjs";
import { renderReadme, recentRepos, linkBadges } from "./lib/readme.mjs";
import { loadConfig } from "./build.mjs";

const cfg = await loadConfig(new URL("../profile.config.json", import.meta.url).pathname);
const repo = (name, extra = {}) => ({
  name,
  html_url: `https://github.com/${cfg.username}/${name}`,
  description: `${name} description`,
  language: "TypeScript",
  stargazers_count: 0,
  pushed_at: "2026-09-01T00:00:00Z",
  ...extra,
});

test("wrap keeps lines within width and marks truncation", () => {
  const lines = wrap("one two three four five six seven eight nine ten", { maxWidth: 60, fontSize: 10, em: 0.5, maxLines: 2 });
  assert.equal(lines.length, 2);
  assert.ok(lines[1].endsWith("…"));
  assert.deepEqual(wrap("short", { maxWidth: 500, fontSize: 10, em: 0.5 }), ["short"]);
});

test("esc and slug are safe for SVG and file names", () => {
  assert.equal(esc(`<a href="x">&'`), "&lt;a href=&quot;x&quot;&gt;&amp;&#39;");
  assert.equal(slug("FormFix AI!"), "formfix-ai");
  assert.equal(slug("अ"), "item");
});

test("every SVG is well-formed enough to have one root and no raw ampersands", () => {
  const svgs = [
    renderHero("dark", cfg),
    renderHero("light", cfg),
    renderCard("dark", cfg.projects[0], 0),
    renderStack("light", cfg.stack),
    renderFooter("dark", "a & b"),
  ];
  for (const svg of svgs) {
    assert.equal(svg.match(/<svg\b/g).length, 1);
    assert.doesNotMatch(svg, /&(?!amp;|lt;|gt;|quot;|#39;)/);
    assert.doesNotMatch(svg, /undefined|NaN/);
  }
});

test("hero rejects typing phrases that would overflow", () => {
  assert.throws(() => renderHero("dark", { ...cfg, hero: { ...cfg.hero, typing: ["x".repeat(80)] } }), /longer than/);
});

test("recent repos skip forks, the profile repo, hidden and featured ones", () => {
  const repos = [
    repo(cfg.username),
    repo("forked", { fork: true }),
    repo("secret", { topics: ["profile-hidden"] }),
    repo("old", { pushed_at: "2025-01-01T00:00:00Z" }),
    repo("new"),
  ];
  const c = { ...cfg, projects: [{ name: "X", description: "x", repo: "new" }] };
  assert.deepEqual(recentRepos(repos, c).map((r) => r.name), ["old"]);
});

test("README only includes sections that have content", () => {
  const empty = renderReadme(cfg, { repos: [], snake: false });
  assert.doesNotMatch(empty, /Recently pushed/);
  assert.doesNotMatch(empty, /snake/);
  const full = renderReadme(cfg, { repos: [repo("side-project")], snake: true });
  assert.match(full, /\[\*\*side-project\*\*\]/);
  assert.match(full, /output\/snake-dark\.svg/);
  for (const p of cfg.projects) assert.match(full, new RegExp(`assets/cards/${slug(p.name)}-dark\\.svg`));
});

test("links: blanks are skipped, bad URLs and unknown keys warn", () => {
  const warnings = [];
  const badges = linkBadges({ website: "https://example.com", x: "@someone", email: "", linkedin: "javascript:alert(1)", myspace: "x" }, (w) => warnings.push(w));
  assert.equal(badges.length, 2);
  assert.match(badges[1], /https:\/\/x\.com\/someone/);
  assert.equal(warnings.length, 2);
});

test("committed files match the config (run `npm run build:offline` if this fails)", async () => {
  const readme = await readFile(new URL("../README.md", import.meta.url), "utf8");
  assert.match(readme, /Generated by scripts\/build\.mjs/);
  const hero = await readFile(new URL("../assets/hero-dark.svg", import.meta.url), "utf8");
  assert.equal(hero, renderHero("dark", cfg));
});
